### ISSUE TITLE
Consider a separate contributor acknowledgement policy

### ISSUE THREAD

**Issue by mellybelly** [ga4gh/ga4gh-copyright-policy#1]
Some relevant standards work on this here: 
https://contributor-attribution-model.readthedocs.io/en/latest/

**Comment by jb-adams** [comment]
@athorogood

**Comment by athorogood** [comment]
Hi Melly, this is a thoughtful suggestion. We are trying to frame GA4GH as a standards development organization that releases community standards, rather than releasing collaborative academic outputs. We want to emphasize that these standards are by and for the GA4GH community. We have asked each Work Stream to find non-legal means of giving contributors recognition and credit, and contributors are also free to publish their contributions separately. There was also concern that legal contributor attribution requirements for these primarily technical specifications would be difficult to manage, and would be a barrier to standards development and adoption, and in some cases has already lead to control issues (that the GA4GH can't easily update standards without single contributor permission). That said, please work with us to make sure Work Streams are finding appropriate non-license means to give contributors appropriate attribution.
